config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  
  root to: "home#top"
  resources :ramen_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :ramen_comments, only: [:create, :destroy]
    
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  
  get 'search/search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :ramen_image
  
end

app/models/ramen_comment.rb
class RamenComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :ramen_image
  
end

app/models/ramen_image.rb
class RamenImage < ApplicationRecord
  
  belongs_to :user
  attachment :image # 画像投稿する為に追加（_idは含めない）
  has_many :ramen_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :shop_name, presence: true
  validates :image, presence: true
  validates :caption, presence: true
  validates :taste, presence: true
  validates :address, presence: true
  validates :tax_price, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search, word) #検索
        if search == "forward_match"
                        @ramen_image = RamenImage.where("taste LIKE?","#{word}%")
        elsif search == "backward_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}%")
        elsif search == "partial_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}%")
        else
                        @ramen_image = RamenImage.all
        end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :ramen_images, dependent: :destroy
  has_many :ramen_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  #フォロー機能のアソシエーション
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end
  
  
  
  def self.search(search,word)#検索機能
          if search == "forward_match"
                          @user = User.where("username LIKE?","#{word}%")
          elsif search == "backward_match"
                          @user = User.where("username LIKE?","%#{word}")
          elsif search == "perfect_match"
                          @user = User.where("username LIKE?","%#{word}%")
          elsif search == "partial_match"
                          @user = User.where("username LIKE?","%#{word}%")
          else
                          @user = User.all
          end 
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :index,]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    ramen_images_path
  end
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    favorite = current_user.favorites.new(ramen_image_id: @ramen_image.id)
    favorite.save
    # render :create
  end

  def destroy
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    favorite = current_user.favorites.find_by(ramen_image_id: @ramen_image.id)
    favorite.destroy
    # render :destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/ramen_comments_controller.rb
class RamenCommentsController < ApplicationController
  
  def create
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    comment = current_user.ramen_comments.new(ramen_comment_params)
    comment.ramen_image_id = @ramen_image.id
    comment.save
  end

  def destroy
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    RamenComment.find_by(id: params[:id], ramen_image_id: params[:ramen_image_id]).destroy
  end
  
  private
  def ramen_comment_params
    params.require(:ramen_comment).permit(:comment)
  end
  
end

app/controllers/ramen_images_controller.rb
class RamenImagesController < ApplicationController
  
  def new
    @ramen_image = RamenImage.new
  end
    #投稿データ保存とバリデーション
  def create
    @ramen_image = RamenImage.new(ramen_image_params)
    @ramen_image.score = Language.get_data(ramen_image_params[:caption])
    @ramen_image.user_id = current_user.id
    if @ramen_image.save
      redirect_to ramen_images_path
    else
      render :new
    end
  end

  def index
    @ramen_images = RamenImage.page(params[:page]).reverse_order
  end

  def show
    @ramen_image = RamenImage.find(params[:id])
    @ramen_comment = RamenComment.new
    @user = @ramen_image.user
  end

  def destroy
    @ramen_image = RamenImage.find(params[:id])
    @ramen_image.destroy
    redirect_to ramen_images_path
  end

  private
  
  def ramen_image_params
    params.require(:ramen_image).permit(:shop_name, :image, :caption, :address, :taste, :tax_price, :evaluation)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_to user_path(current_user.id)
  end
  
  def unfollow
    current_user.unfollow(params[:id])
    redirect_to user_path(current_user.id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @range = params[:range].to_i
    search = params[:search]
    word = params[:word]

    if @range == 1
     @user = User.search(search,word)
    else
     @ramen_image = RamenImage.search(search,word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @ramen_images = @user.ramen_images.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
  params.require(:user).permit(:username, :profile_image, :profile)
  end
  
  def correct_user
    user = User.find(params[:id])
    redirect_to root_url if current_user != user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ramen_comments_helper.rb
module RamenCommentsHelper
end

app/helpers/ramen_images_helper.rb
module RamenImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
 <br/>
 <div>
 <!--いいね機能-->
  <% if ramen_image.favorited_by?(current_user) %>
    <p>
      <%= link_to ramen_image_favorites_path(ramen_image), remote: true, method: :delete do %>
          <i class="fas fa-battery-full green fa-3x">
            <%= ramen_image.favorites.count %>
          </i>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to ramen_image_favorites_path(ramen_image), remote: true, method: :post do %>
        <i class="fas fa-battery-quarter red fa-3x">
          <%= ramen_image.favorites.count %>
        </i>
      <% end %>
    </p>
  <% end %>
</div>

app/views/favorites/create.js.erb
$("#ramen_image_<%= @ramen_image.id %>").html("<%= j(render 'favorites/favorite', ramen_image: @ramen_image) %>");

app/views/favorites/destroy.js.erb
$("#ramen_image_<%= @ramen_image.id %>").html("<%= j(render 'favorites/favorite', ramen_image: @ramen_image) %>");

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/top.html.erb
<div class="jumbotron jumbotron-extend">
    <div class="container-fluid jumbotron-container">
        <h1 class="site-name">
            思い出の一杯をいっぱいに。。
        </h1>
       <%= link_to "Log in", new_user_session_path, class:"btn btn-dark" %>
       <%= link_to "Sign Up", new_user_registration_path,class:"btn btn-dark" %>
    </div>
</div>

app/views/ramen_comments/_form.html.erb
<div>
  <%= form_with model:[@ramen_image, @ramen_comment] do |f| %>
   
    <%= f.text_area :comment, rows:'3',placeholder: "コメント" %><br/>
    <%= f.submit "コメントを追加", class: "btn btn-secondary" %>
  <% end %>
  <br/>
</div>

app/views/ramen_comments/_index.html.erb
<!--コメント表示-->
<% ramen_image.ramen_comments.each do |ramen_comment| %>
    <div class="color">
          <%= attachment_image_tag ramen_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <%= ramen_comment.comment %><br/>
          <%= ramen_comment.user.username %>
           <!--コメント削除  -->
          <% if ramen_comment.user == current_user %>
            <%= link_to ramen_image_ramen_comment_path(ramen_comment.ramen_image, ramen_comment), method: :delete, remote: true do %>
              <i class="fas fa-trash-alt fa-2x"></i>
            <% end %>
          <% end %>
   </div>
<% end %>

app/views/ramen_comments/create.js.erb
$("#comments").html("<%= j(render 'ramen_comments/index', ramen_image: @ramen_image) %>")
$("textarea").val('')

app/views/ramen_comments/destroy.js.erb
$("#comments").html("<%= j(render 'ramen_comments/index', ramen_image: @ramen_image) %>")

app/views/ramen_images/_gmap.html.erb
<!-- 地名入力用のinputを追加 -->
<input id="address" type="textbox" value="<%= ramen_image.address %>">

<!-- buttonをクリックしたらcodeAddressを実行　-->
<input type="button" value="Encode" onclick="codeAddress()">
<div id='map'>
</div>

<style>
#map{
  height: 400px;
}
</style>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 15
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLh8k-f2_I9F9TAe3WcQJCMtRcqY3Vi8g&callback=initMap" async defer></script>

app/views/ramen_images/_list.html.erb
<div class="card-list-containar">
  <% ramen_images.each do |ramen_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <h4>
      <%= attachment_image_tag ramen_image.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <%= ramen_image.user.username %>
    </h4>
    <div class="image">
      <%= link_to ramen_image_path(ramen_image.id) do %>
      <%= attachment_image_tag ramen_image, :image, :fill, 720, 720, format: 'jpeg', fallback: "no_image.jpg" %>
      <% end %>
    </div>
    <div class="card-body">
        <div class="row">
          <div class="col-6">
           店舗名
            <p><i class="fas fa-arrow-alt-circle-right fa-lg"></i> <%= ramen_image.shop_name %></p>
           税込価格  
            <p><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= ramen_image.tax_price %>円</p>
          </div>
          <div class="col-6">
            スープ
            <P><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= ramen_image.taste %></P>
            評価
             <div class="ramen_image-evaluation" data-score="<%= ramen_image.evaluation %>"></div>
            
        </div>
    </div>
  </div>  
</div>
<% end %>
<script>
  $('.ramen_image-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
  });
</script>
<br/>
<%= paginate ramen_images %>

app/views/ramen_images/index.html.erb
<%= render 'ramen_images/list', ramen_images: @ramen_images %>

app/views/ramen_images/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class='px-3 mx-auto'>
      <div class="card post">
        <h1><i class="fas fa-camera-retro"></i></h1>
        
        
        <% if @ramen_image.errors.any? %>
          <%= @ramen_image.errors.count %>件のエラーが発生しました
          <p><% @ramen_image.errors.full_messages.each do |message| %></p>
            <%= message %>
          <% end %>
        <% end %>
        
        
        <%= form_with model: @ramen_image, local:true do |f| %>
          <%= f.attachment_field :image %>
          <h4>店舗名</h4>
          <%= f.text_field :shop_name %>
          <h4>住所</h4>
          <%= f.text_field :address %>
          <h4>税込価格</h4>
          <%= f.text_field :tax_price %>
          <h4>スープ</h4>
          <%= f.text_field :taste %>
          <h4>感想</h4>
          <%= f.text_area :caption %>
          <div id="evaluate_stars">
            <label>評価</label>
          </div>
          <%= f.submit '投稿', class:"btn btn-outline-secondary" %>
        <% end %>
        
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'ramen_image[evaluation]' //登録するモデル名とカラム名を記述
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/ramen_images/show.html.erb
<div class="card mb-3" style="max-width: 1600px">
  <div class="row no-gutters">
          <div class="col-md-5 my-auto">
            <!--投稿詳細-->
            <%= link_to user_path (@user) do %>
            <div class="image">
            </div>
            <%= attachment_image_tag @ramen_image, :image, :fill, 500, 500, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
            <div><%= @ramen_image.created_at.strftime('%Y/%m/%d') %></div>
          </div>
          
          
          <div class="col-md-3">
            <h3>ラーメン情報</h3>
            <div>
                <p>店舗名<br/><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= @ramen_image.shop_name %></p>
                <p>住所<br/><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= @ramen_image.address %></p>
                <p>税込価格<br/><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= @ramen_image.tax_price %>円</p>
                <p>スープ<br/><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= @ramen_image.taste %></p>
                <p>感想<br/><i class="fas fa-arrow-alt-circle-right fa-lg"></i><%= @ramen_image.caption %></p>
                <p>
                <h4>ポジティブ指数　<%= @ramen_image.score * 100 %>点</h4>※AIの感情分析を用いて投稿された感想が<br/>ポジティブな内容かネガティブな内容かを<br/>判断しています。
                </p>
                <div>評価</div>
                  <div class="ramen_image-evaluation" data-score="<%= @ramen_image.evaluation %>"></div>
                    <script>
                      $('.ramen_image-evaluation').raty({
                        readOnly: true,
                        score: function() {
                          return $(this).attr('data-score');
                        },
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                      });
                    </script>
                
                <div id="ramen_image_<%= @ramen_image.id %>">
                <!--いいね機能-->
                <%= render 'favorites/favorite', ramen_image: @ramen_image %>
                </div>
                <!--投稿削除-->
              <% if @ramen_image.user == current_user %>
                  <h4>
                  <%= link_to ramen_image_path(@ramen_image), method: :delete do %>
                  <button type="button" class="btn btn-outline-secondary">投稿削除</button>
                  </h4>
                <% end %>
              <% end %> 
                
            </div>
          </div>
            
          <div class="col-md-4 comment">
            <h3>麺バーのコメント</h3>
              <!--コメント一覧-->
              <div id = "comments">
              <%= render 'ramen_comments/index', ramen_image: @ramen_image %>
              </div>
              <!--コメント投稿-->
              <br/>
              <div class="new-comment">
              <%= render 'ramen_comments/form', ramen_image: @ramen_image %>
              </div>
               
          </div>
        </div>
      </div>
  </div>
</div>
            
              
              
<!--マップ表示-->
<%= render 'ramen_images/gmap', ramen_image: @ramen_image %>

app/views/search/search.html.erb
<table class="table table-hover table-inverse">
<% if @range == 2 %>
<thead>
    <tr>
     <th></th>
     <th>スープ</th>
     <th>評価</th>
     <th>店舗名</th>
     <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @ramen_image.each do |ramen_image| %>
     <tr>
      <td>
        <%= link_to ramen_image_path(ramen_image.id) do %>
            <%= attachment_image_tag ramen_image, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= ramen_image.taste %></td>
      <td class="ramen_image-evaluation" data-score="<%= ramen_image.evaluation %>"></td>
      <td><%= ramen_image.shop_name %></td>
     </tr>
     <% end %>
     <script>
      $('.ramen_image-evaluation').raty({
        readOnly: true,
        score: function() {
          return $(this).attr('data-score');
        },
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
      });
     </script>
  </tbody>
  <% elsif @range == 1 %>
  <thead>
     <tr>
      <th></th>
      <th>ユーザーネーム</th>
      <th>プロフィール</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td>
        <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
        <% end %>
      </td>
      <td><%= user.username%></td>
      <td><%= user.profile%></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/edit.html.erb
<div class="card" style="width: 100rem; height: 25rem;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <br/><h2>ユーザー編集</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :"アイコン", class:"form-label" %>
            <%= f.attachment_field :profile_image, placeholder: "", class:"form-control-file user_image" %>
          </div>
          <div class="form-group">
            <%= f.label :"名前", class:"form-label" %>
            <%= f.text_field :username, class:"form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :"プロフィール", class:"form-label" %>
            <%= f.text_field :profile, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<table class="table table-hover table-inverse">
<thead>
     <tr>
      <th></th>
      <th>ユーザーネーム</th>
      <th>プロフィール</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% User.all.where.not(id: current_user.id).each do |user| %>
     <tr>
      <td>
        <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= user.username %></td>
      <td><%= user.profile %></td>
      <td>
        <% if current_user.following?(user) %>
          <%= link_to unfollow_path(user.id), method: :POST do %>
          <button type="button" class="btn btn-info">フォロー外す</button>
          <% end %>
          <% else %>
          <%= link_to follow_path(user.id), method: :POST do%>
          <button type="button" class="btn btn-primary">フォローする</button>
          <% end %>
        <% end %>
      </td>
     </tr>
    <% end %>
   </tbody>
</table>

app/views/users/show.html.erb
<div class="card mb-3" style="max-width: 1600px">
  <div class="row no-gutters">
          <div class="col-md-2 image">
            <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg" %>
          </div>
          <div class="col-md-3 image">
            <label>ユーザーネーム</label>
            <br/><h4><%= @user.username %></h4><br/>
            <label>プロフィール</label>
            <br/><h4><%= @user.profile %></h4><br/>
             <% unless @user == current_user %>
                <% if current_user.following?(@user) %>
                  <%= link_to  unfollow_path(@user.id), method: :POST do %>
                  <button type="button" class="btn btn-info">フォロー外す</button>
                  <% end %>
                <% else %>
                  <%= link_to follow_path(@user.id), method: :POST do%>
                  <button type="button" class="btn btn-primary">フォローする</button>
                  <% end %>
                <% end %>
              <% end %>
             <% if @user.id == current_user.id %>
              <p>
                <%= link_to edit_user_path(@user) do %>
                  <button type="button" class="btn btn-secondary">編集</button>
                <% end %>
              </p>
             <% end %>
          </div>
          
          <div class="col-md-4 image">
            <p><h4><%= "フォロー #{@user.follower.count}名" %></h4></p>
            <!--フォロー一覧表示-->
              <% @user.following_user.where.not(id: current_user.id).each do |user| %>
            <p>
                <%= link_to user_path(user) do%>
                     <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
                <%= user.username %>
              <div>
                <% if current_user.following?(user) %>
                  <%= link_to unfollow_path(user.id), method: :POST do %>
                  <button type="button" class="right btn btn-info">フォロー外す</button>
                  <% end %>
                <% else %>
                  <%= link_to follow_path(user.id), method: :POST do %>
                  <button type="button" class="right btn btn-primary">フォローする</button>
                  <% end %>
                <% end %>
              </div>
            </p>
              <% end %>
          </div>
          
          <div class="col-md-3 image">
             <p><h4><%= "フォロワー #{@user.followed.count}名" %></h4></p>
              <!--フォロワー一覧表示-->
              <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
                <p>
                  <%= link_to user_path(user) do%>
                   <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                  <%= user.username %>
                <div>
                  <% if current_user.following?(user) %>
                    <%= link_to unfollow_path(user.id), method: :POST do %>
                    <button type="button" class="btn btn-info">フォロー外す</button>
                    <% end %>
                  <% else %>
                    <%= link_to follow_path(user.id), method: :POST do %>
                    <button type="button" class="btn btn-primary">フォローする</button>
                    <% end %>
                  <% end %>
                </div>
                </p>
              <% end %>
              
             
          </div>
  </div>
</div>
  
  
  
  
  
 
  
  
</div>

<%= render 'ramen_images/list', ramen_images: @ramen_images %>