config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  
  root to: "home#top"
  resources :ramen_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :ramen_comments, only: [:create, :destroy]
    
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  
  get 'search/search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :ramen_image
  
end

app/models/ramen_comment.rb
class RamenComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :ramen_image
  
end

app/models/ramen_image.rb
class RamenImage < ApplicationRecord
  
  belongs_to :user
  attachment :image # 画像投稿する為に追加（_idは含めない）
  has_many :ramen_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :shop_name, presence: true
  validates :image, presence: true
  validates :caption, presence: true
  validates :taste, presence: true
  validates :address, presence: true
  validates :tax_price, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search, word) #検索
        if search == "forward_match"
                        @ramen_image = RamenImage.where("taste LIKE?","#{word}%")
        elsif search == "backward_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}%")
        elsif search == "partial_match"
                        @ramen_image = RamenImage.where("taste LIKE?","%#{word}%")
        else
                        @ramen_image = RamenImage.all
        end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :ramen_images, dependent: :destroy
  has_many :ramen_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  #フォロー機能のアソシエーション
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end
  
  
  
  def self.search(search,word)#検索機能
          if search == "forward_match"
                          @user = User.where("username LIKE?","#{word}%")
          elsif search == "backward_match"
                          @user = User.where("username LIKE?","%#{word}")
          elsif search == "perfect_match"
                          @user = User.where("username LIKE?","%#{word}%")
          elsif search == "partial_match"
                          @user = User.where("username LIKE?","%#{word}%")
          else
                          @user = User.all
          end 
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :index,]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    ramen_images_path
  end
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    favorite = current_user.favorites.new(ramen_image_id: @ramen_image.id)
    favorite.save
    # render :create
  end

  def destroy
    @ramen_image = RamenImage.find(params[:ramen_image_id])
    favorite = current_user.favorites.find_by(ramen_image_id: @ramen_image.id)
    favorite.destroy
    # render :destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/ramen_images_controller.rb
class RamenImagesController < ApplicationController
  
  def new
    @ramen_image = RamenImage.new
  end
    #投稿データ保存とバリデーション
  def create
    @ramen_image = RamenImage.new(ramen_image_params)
    @ramen_image.score = Language.get_data(ramen_image_params[:caption])
    @ramen_image.user_id = current_user.id
    if @ramen_image.save
      redirect_to ramen_images_path
    else
      render :new
    end
  end

  def index
    @ramen_images = RamenImage.page(params[:page]).reverse_order
  end

  def show
    @ramen_image = RamenImage.find(params[:id])
    @ramen_comment = RamenComment.new
    @user = @ramen_image.user
  end

  def destroy
    @ramen_image = RamenImage.find(params[:id])
    @ramen_image.destroy
    redirect_to ramen_images_path
  end

  private
  
  def ramen_image_params
    params.require(:ramen_image).permit(:shop_name, :image, :caption, :address, :taste, :tax_price, :evaluation)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @range = params[:range].to_i
    search = params[:search]
    word = params[:word]

    if @range == 1
     @user = User.search(search,word)
    else
     @ramen_image = RamenImage.search(search,word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @ramen_images = @user.ramen_images.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
  params.require(:user).permit(:username, :profile_image, :profile)
  end
  
  def correct_user
    user = User.find(params[:id])
    redirect_to root_url if current_user != user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ramen_comments_helper.rb
module RamenCommentsHelper
end

app/helpers/ramen_images_helper.rb
module RamenImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand p-3">
        <%= link_to root_path, class: 'nav-link text-dark' do %>
            <h1 class="title is-4" style="font-family: cursive;">麺stagram
            <i class="fab fa-instagram instagram"></i>
            </h1>
        <% end %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to '投稿', new_ramen_image_path, class: 'fas fa-camera-retro nav-link text-dark'%> 
                  </li>
                  <li class="nav-item">
                    <%= link_to 'マイページ', user_path(current_user.id), class: 'fas fa-user nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ラーメン', ramen_images_path, class: 'fas fa-mortar-pestle nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '麺バー', users_path(current_user.id), class: 'fas fa-child nav-link text-dark' %>
                  </li>
                   <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-dark' %>
                  </li>
            <% else %>
                  <li class="nav-item">
                    <%= link_to 'ラーメン', ramen_images_path, class: 'fas fa-mortar-pestle nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_user_registration_path, class: 'fas fa-user-plus nav-link text-dark' %>
                  </li>
            <% end %>
          </ul>
            <% if user_signed_in? %>
                    <%= form_tag(search_search_path, method: :get) do %>
                    <%= select_tag 'range' ,options_for_select([['スープ', '2'], ['麺バー', '1']]) %>
                    <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"], ["完全一致","perfect_match"]]) %>
                    <%= text_field_tag (:word) %>
                    <%= submit_tag "🔍" %>
                    <% end %>
            <% end %>
        </div>
  </nav>
  
  
</header>
    
    
    <%= yield %>
    
  </body>
</html>